---
# Usage:
# docker-compose build
# docker-compose down; docker-compose up --build --detach

version: '3.8'

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
